# This is a basic workflow to help you get started with Actions

name: Produce_graphics

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Convert notebook to script and run
        run: |
          sudo apt install -y pip jupyter
          pip install -r requirements.txt
          jupyter nbconvert 2021-now-graph-per-cause-area.ipynb --to script
          python 2021-now-graph-per-cause-area.py

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: 2021-now-graph-per-cause-area.png
            commit-msg: Upload autogenerated image
            github-token: ${{ secrets.GITHUB_TOKEN }}