# This is a basic workflow to help you get started with Actions

name: Produce_graphics

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup environment
        run: |
          sudo apt install -y pip jupyter
          pip install -r requirements.txt

      - name: Produce graphs
        run: |
          mkdir -p pngs
          shopt -s nullglob
          for i in *; do
            jupyter nbconvert ${i} --to script --output ${i}.py
            python ${i}.py
          done

      - name: Commit graphs
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add pngs
          git commit -m "Upload graphs"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
